---

- name: Needrestart Tasks
  tags:
    - needrestart_install
    - needrestart_config
    - needrestart
  block:
    - name: Set dependency variables
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_os_family }}/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - name: Install tasks 
      ansible.builtin.import_tasks: install.yml
    - name: Configration tasks 
      ansible.builtin.import_tasks: config.yml
    - name: Dropin configration tasks 
      ansible.builtin.import_tasks: dropin.yml
  rescue:
    - name: Print Error
      ansible.builtin.debug:
        msg: "Unsupport platform or error occurred due to some reason."
      failed_when: true
